services:
  haproxy:
    image: haproxy:3.0
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8404:8404"
      - "5432:5432"
      - "6380:6379"
      - "8500:8500"

  consul1:
    image: consul:1.15
    command: agent -server -bootstrap-expect=3 -ui -node=server-1 -client=0.0.0.0
    volumes:
      - consul1-data:/consul/data

  consul2:
    image: consul:1.15
    command: agent -server -bootstrap-expect=3 -ui -node=server-2 -retry-join=consul1 -client=0.0.0.0
    volumes:
      - consul2-data:/consul/data

  consul3:
    image: consul:1.15
    command: agent -server -bootstrap-expect=3 -ui -node=server-3 -retry-join=consul1 -client=0.0.0.0
    volumes:
      - consul3-data:/consul/data

  patroni1:
    image: patroni
    command: /usr/local/bin/entrypoint.sh /etc/patroni.yml
    volumes:
      - patroni1-data:/data/patroni
      - ./patroni.yml:/etc/patroni.yml
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh

  patroni2:
    image: patroni
    volumes:
      - patroni2-data:/data/patroni
      - ./patroni.yml:/etc/patroni.yml
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    command: /usr/local/bin/entrypoint.sh /etc/patroni.yml

  sentinel1:
    image: redis:7.2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf

  sentinel2:
    image: redis:7.2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf

  sentinel3:
    image: redis:7.2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf

  redis1:
    image: redis:7.2
    command: redis-server --requirepass mypassword --masterauth mypassword
    volumes:
      - redis1-data:/data

  redis2:
    image: redis:7.2
    command: redis-server --slaveof redis1 6379 --requirepass mypassword --masterauth mypassword
    volumes:
      - redis2-data:/data

  gitlab:
    image: zengxs/gitlab:17.5.0-ce.0
    ports:
      - "8000:8000"
      - "443:443"
      - "22:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8000'

        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_host'] = "haproxy"
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_username'] = "postgres"
        gitlab_rails['db_password'] = "postgres"
        gitlab_rails['db_database'] = "gitlab"

        gitlab_rails['redis_host'] = "haproxy"
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_password'] = "mypassword"

        postgresql['enable'] = false
        redis['enable'] = false

        gitlab_rails['initial_root_password'] = 'insecure-kPe5qrk*pgr6zjf'
        gitlab_rails['initial_root_email'] = 'admin@local'
    volumes:
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

volumes:
  consul1-data:
  consul2-data:
  consul3-data:
  patroni1-data:
  patroni2-data:
  redis1-data:
  redis2-data:
  gitlab-logs:
  gitlab-data:
