---
- name: Initialize Swarm
  become: true
  hosts: all
  roles:
    - docker
    - swarm

- name: Initialize GlusterFS
  become: true
  hosts: all
  roles:
    - glusterfs

- name: Deploy GitLab
  become: true
  hosts: all
  roles:
    - gitlab
