scope: patroni
namespace: /service/

watchdog:
  mode: off

consul:
  host: gateway:8500
  register_service: true
  service_tags:
    - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
    - "traefik.tcp.routers.postgres.entrypoints=postgres"
    - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"

postgresql:
  data_dir: /data/patroni
  bin_dir: /usr/lib/postgresql/17/bin
  pgpass: /tmp/pgpass
  parameters:
    unix_socket_directories: '.'

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true

  postgresql:
    use_pg_rewind: true

  initdb:
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - host replication all all md5
    - host all all all md5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
